package-config:
  do-package: "com.wilimm.practise.spring.entity"
  dao-package: "com.wilimm.practise.spring.dao"
  java-src-path: D:\work\github\java-practise\spring\src\main\java
  xml-path: D:\work\github\java-practise\spring\src\main\resources\mybatis