package-config:
  do-package: "me.huakai.domain.entity"
  dao-package: "me.huakai.querydao"
  java-src-path: D:\work\project\api\core\src\main\java
  xml-path: D:\work\project\api\core\src\main\resources\mysql\mybatis